import Head from "next/head";
import { Inter } from "@next/font/google";
import Card from "../components/styled/blocks/Card";
import Button from "../components/styled/elements/Button";
import PokeCard from "../components/styled/blocks/PokemonCard";

const inter = Inter({ subsets: ["latin"] });



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true' />

      </Head>
      <main style={{ height: 100 + "vh", background: 'black', }}>

        <Button rippleOff activated color='#ff00ff' glow >Default</Button>
        <Button activated color='#24acf2' glow >Default</Button>
        <Button activated color='orange' glow >Default</Button>
        <Button color='yellow' glow >Default</Button>
        <Button color='green' glow >Default</Button>
        <Button color='blue' glow >Default</Button>
        <Button color='indigo' glow >Default</Button>
        <Button color='violet' glow >Default</Button>
        <Button bevel color='white' >Default</Button>
        <Button color='red' >Default</Button>
        <Button color='orange' >Default</Button>
        <Button color='yellow' >Default</Button>
        <Button color='green' >Default</Button>
        <Button  color='blue' >Default</Button>
        <Button color='indigo' >Default</Button>
        <Button color='violet' >Default</Button>
        <Button>Default</Button>

        <div style={{display: 'flex', flexWrap: 'wrap', justifyContent: "center",}}>
        <Card>
          <Card.Header>
            <Card.Image
              src="https://github.com/NateAyye.png"
              alt="Card Picture"
            />
            <Card.Title>Nathan Cuevas</Card.Title>
          </Card.Header>
          <Card.Text>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt nesciunt nemo veniam eveniet? Libero quasi fugiat vero quos, eos rem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est molestiae et consequuntur laudantium velit architecto porro nesciunt maiores saepe corporis! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Est eaque suscipit, porro iure perferendis illo unde eos temporibus atque natus.
          </Card.Text>
        </Card>
        <Card>
          <Card.Header>
            <Card.Image
              src="https://github.com/NateAyye.png"
              alt="Card Picture"
            />
            <Card.Title>Nathan Cuevas</Card.Title>
          </Card.Header>
          <Card.Text>
            Wellcome to the Card made from styled components
          </Card.Text>
        </Card>
        <PokeCard type='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSa96H_h4g735h8p0ciVKgpq3LUwkBUBYM0s1ytzPjBe4vf1FzKrfU-DHUnkkelakUfPug&usqp=CAU' title='Ditto' src='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png' />
        </div>
      </main>
    </>
  );
}
