import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Button, { DarkButton, NeonButton, RippleButton } from "../components/styled/blocks/Button";
import Card from "../components/styled/blocks/Card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  if (typeof document !== "undefined") {
  const buttons = document.querySelectorAll('a');
  buttons.forEach(btn => {
    btn.addEventListener('click', (e) => {
      let x = e.clientX - e.target.offsetLeft;
      let y = e.clientY - e.target.offsetTop;

      let ripples = document.createElement('span');
      ripples.style.left = x + 'px';
      ripples.style.top = y + 'px';
      btn.appendChild(ripples);

      setTimeout(() => {
        ripples.remove();
      }, 1000)
    })
  })
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ height: 100 + "vh" }}>
        <DarkButton> Button </DarkButton>
        <NeonButton>Home</NeonButton>
        <Button>Button</Button>
        <Button primary>Button</Button>
        <RippleButton>Ripple</RippleButton>
        <div style={{display: 'flex', flexWrap: 'wrap', justifyContent: "center",}}>
        <Card>
          <Card.Header>
            <Card.Image
              src="https://github.com/NateAyye.png"
              alt="Card Picture"
            />
            <Card.Title>Nathan Cuevas</Card.Title>
          </Card.Header>
          <Card.Text>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt nesciunt nemo veniam eveniet? Libero quasi fugiat vero quos, eos rem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est molestiae et consequuntur laudantium velit architecto porro nesciunt maiores saepe corporis!
          </Card.Text>
        </Card>
        <Card>
          <Card.Header>
            <Card.Image
              src="https://github.com/NateAyye.png"
              alt="Card Picture"
            />
            <Card.Title>Nathan Cuevas</Card.Title>
          </Card.Header>
          <Card.Text>
            Wellcome to the Card made from styled components
          </Card.Text>
        </Card>
        </div>
      </main>
    </>
  );
}
